# Generated by Django 4.1.5 on 2024-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("file", models.FileField(upload_to="")),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium")], max_length=10
                    ),
                ),
            ],
        ),
    ]
